### ISSUE TITLE
How to handle NaN values in the UCR data sets?

### ISSUE THREAD

**Issue by ShaowuChen** [angus924/rocket#10]
Hello,

I just learn the amazing Rocket and MiniRocket recently. When I used them to classify some UCRArchive2018 datasets (such as 'DodgerLoopGame'), NaN values representing missing values caused Errors.  Therefore, I wonder how you handle these values? Is it approriate to directly delete samples with NaN values?

Thanks for your help!

**Comment by angus924** [comment]
Hi @ShaowuChen, sorry for the very slow response.  I would suggest either replacing the nan values with zeros, or do linear interpolation.
