### ISSUE TITLE
Multivariate implementation of rocket.

### ISSUE THREAD

**Issue by YunruiZhang** [angus924/rocket#11]
Hi, I wonder if a multivariant implementation of the rocket is available?

**Comment by YunruiZhang** [comment]
It seems like there is a multivariant version of the rocket on sktime [https://github.com/sktime/sktime/blob/157600f9592b68c2448f0665ecf37edbad98d221/sktime/transformations/panel/rocket/_rocket.py#L16](url), but it's implementation is quite different to what is here and what is described in the paper. And I found it hard to understand without comments.

**Comment by angus924** [comment]
Sorry for the late reply.

The multivariate version of Rocket in sktime is based on code I originally provided, but I'm not 100% sure how it has been changed or updated since.  From a quick look, the basic code looks more or less in it's original form.
