### ISSUE TITLE
normalized features

### ISSUE THREAD

**Issue by YunruiZhang** [angus924/rocket#13]
Hi,

I found that in multi-rocket the features are not normalized when fed into the ridge classifier, While they are normalized in rocket and mini-rocket. I wonder if there is any reason the features are normalized, and in the case of the features being normalized, I wonder why the MAXs and PPVs are normalized together instead of normalized individually.

Thank you in advance.
Yunrui

**Comment by angus924** [comment]
Sorry for the slow response.

If you could point me to the exact code, I might be able to check more specifically what's going on.

With Rocket, MiniRocket, and MultiRocket, the transformed features should be normalised before being used to fit the ridge classifier.  The default approach for the ridge classifier is to subtract the mean and divide by the L2 norm *per feature* (i.e., the features are not normalised together, they are all normalised independently).  Alternatively, you could subtract the mean and divide by the standard deviation (again, per feature), both approaches should produce similar results.
