### ISSUE TITLE
Per-feature normalization

### ISSUE THREAD

**Issue by oguiza** [angus924/rocket#2]
Hi Angus,

First of all congrats on your new TSC method. I've used it and the results are very good, and super fast compared to other methods!

I've noticed a discrepancy between the bake-off and the scalable codes you've shared.
In the scalable, you perform a per-feature normalization while you don't do that in the bake-off. 
Is there any reason for that? I've run a few tests with some bake-off datasets and have seen that this per-feature normalization hurts performance.

**Comment by angus924** [comment]
Hi Ignacio,

Great question.

Actually, we perform per-feature normalisation for both the 'bake off' datasets and for the scalability experiments (number of training examples), but using a different approach in each case:

* for the 'bake off' datasets, we perform per-feature normalisation using the 'normalize = True' argument of RidgeClassifierCV, which works by subtracting the per-feature mean and dividing by the per-feature l2 norm (this seems to work best for the ridge regression classifier); and
* for the scalability experiments, we perform normalisation 'manually', by subtracting the per-feature mean and dividing by the per-feature standard deviation (this seems to work best for logistic regression).

As you say, the second approach (dividing by the per-feature standard deviation) does not seem to work as well with the ridge regression classifier.

I hope this helps!

(I'll include this point when I update the documentation.)

Thanks.

Best,

Angus.

**Comment by oguiza** [comment]
Thanks for your detailed reply Angus. It's very clear.
I'll close this issue.
