### ISSUE TITLE
How to use it for multivariate time-series?

### ISSUE THREAD

**Issue by bab-git** [angus924/rocket#5]
Hi,
How can I use it for Multivariate time-series (multi-dimension time-series)? 

Thanks,

**Comment by angus924** [comment]
Hi Babak,

There is a multivariate-ready version currently in a pull request in sktime [here](https://github.com/alan-turing-institute/sktime/blob/d408075b91ee1151ff82cbf35116dc5fc816fdcd/sktime/transformers/rocket.py).  (This isn't an 'official' / published multivariate version, but it does provide basic multivariate capability.)

Please let me know if you need any help in using this code.

Thanks very much.

Best,

Angus.

**Comment by bab-git** [comment]
Dear Angus,

Thank you very much for the link.

Best,
Babak

**Comment by bab-git** [comment]
oh BTW, I was wondering how easy we can compute the MAC for this method? 
Indeed, the computational complexity is a key factor in our task.

Thank you!
