### ISSUE TITLE
Application of kernels to multivariate data

### ISSUE THREAD

**Issue by MJFlynn** [angus924/rocket#7]
Hi,

I notice that that the ROCKET transform implemented in sktime now supports the transformation of multivariate datasets.
I was wondering whether you could detail how it is applied?

Many thanks.

**Comment by angus924** [comment]
The only difference is that the kernels operate on multiple channels.  We assign a random subset of channels to each kernel (from 1 up to the smaller of the length of the kernel or the total number of channels).  Kernels assigned to more than one channel are essentially standard 2d kernels applied per the standard 2d convolution operation, i.e., each such kernel gets a set of weights per channel and is applied across all of its assigned channels.  (In other words, this is the same as convolving a 2d kernel with an image, except that here the kernels only 'move' horizontally in the direction of time, rather both horizontally and vertically across an image.)

There is a huge number of possible configurations.  This implementation is only really intended to provide a baseline multivariate capability.  Informally, it seems to work ok, and is an improvement (esp. computationally) on, e.g., always applying all kernels across all chanels.  I don't know much about how it stacks up against other possible configurations or other methods.

**Comment by MJFlynn** [comment]
Hi Angus,

Thanks for the swift reply and clear explanation.

Many thanks.
