### ISSUE TITLE
Satellite Image Time Series (SITS) dataset

### ISSUE THREAD

**Issue by stevcabello** [angus924/rocket#8]
Hi I'd like to reproduce the scalability experiment using the SITS dataset mentioned in the paper. Is this dataset publicly available? If so, where can I find it? 

Thanks =)

**Comment by angus924** [comment]
A version of the dataset is publicly available here: https://figshare.com/articles/dataset/Dataset/4557349.

I don't know what the exact relationship is between this version and the version I was given access to for the purposes of the paper (of which this version is a subset, I think).  It looks like this version has been divided into cross-validation folds.  You might want to concatenate the data or read it fold by fold.

In practice, this version should at least be sufficient for getting some idea of training time in relation to training set size.  (In the bigger picture, it's worth bearing in mind that the time series in this dataset are relatively short.  A 'smaller' dataset with longer time series should be equally as challenging.)
