### ISSUE TITLE
Can output class-probabilities? TS must be same length?

### ISSUE THREAD

**Issue by Ferran-pv** [angus924/rocket#9]
Hi,

I would like to know if, instead of the predicted class, I can know the probability of being in that class. Also, if it allows for time series with different lengths.

regards,
Ferran

**Comment by angus924** [comment]
Hi @Ferran-pv,

Sorry for the slow reply.

The ridge classifier which we use by default for smaller datasets does not output class probabilities.  However, in many cases you can use logistic regression (e.g., from sklearn) instead, without much change in accuracy.  If you use logistic regression you will be able to output class probabilities.

For time series of different lengths, there are a couple of different approaches.  One is to simply pad shorter time series to be all the same length.  The other approach is to edit this line of code (line 44 in `rocket_functions.py`) in the `generate_kernels(...)` function, from:

```python
padding = ((_length - 1) * dilation) // 2 if np.random.randint(2) == 1 else 0
```

to this

```python
padding = ((_length - 1) * dilation) // 2
```

That way, the kernels should run on time series of any length.

Does this help?

Thanks very much.

Best,

Angus

**Comment by Ferran-pv** [comment]
Yes, it does help, thank you very much

Ferran
